/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLNS.View;

import QLNS.Model.NhanVien;
import QLNS.Threading.ClockThread;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainJFrame extends javax.swing.JFrame {

    NhanVien nvLogIn;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        nvLogIn = LoginForm.nvLogIn;
        this.setTitle("NONGSANSACH - " + nvLogIn.getTenNV());

        if (!nvLogIn.getBoPhan().equals("Quản lý")) {
            btnNhanVien.setEnabled(false);
             btnThongke.setEnabled(false);
         

        }

        initClock();
    }

    private void initClock() {
        ClockThread th = new ClockThread(lblClock, "hh:mm:ss aa");
        th.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblClock = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnKhachHang = new javax.swing.JButton();
        btnNongSan = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        txtRun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 161, 12));

        jLabel2.setBackground(new java.awt.Color(1, 181, 10));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("                     NÔNG SẢN SẠCH");

        lblClock.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblClock.setForeground(new java.awt.Color(255, 255, 255));
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblClock.setText("8:8:8 AM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClock, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setLayout(null);

        btnKhachHang.setBackground(new java.awt.Color(123, 224, 219));
        btnKhachHang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnKhachHang.setForeground(new java.awt.Color(0, 102, 0));
        btnKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/customer-icon.png"))); // NOI18N
        btnKhachHang.setText("Quản lý Khách hàng");
        btnKhachHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKhachHang.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseExited(evt);
            }
        });
        btnKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachHangActionPerformed(evt);
            }
        });
        jPanel1.add(btnKhachHang);
        btnKhachHang.setBounds(290, 70, 190, 110);

        btnNongSan.setBackground(new java.awt.Color(123, 224, 219));
        btnNongSan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNongSan.setForeground(new java.awt.Color(0, 102, 0));
        btnNongSan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/apple-icon.png"))); // NOI18N
        btnNongSan.setText("Quản lý Nông sản");
        btnNongSan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNongSan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNongSan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNongSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNongSanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNongSanMouseExited(evt);
            }
        });
        btnNongSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNongSanActionPerformed(evt);
            }
        });
        jPanel1.add(btnNongSan);
        btnNongSan.setBounds(50, 70, 190, 110);

        btnNhanVien.setBackground(new java.awt.Color(123, 224, 219));
        btnNhanVien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(0, 102, 0));
        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/user-con.png"))); // NOI18N
        btnNhanVien.setText("Quản lý Nhân viên");
        btnNhanVien.setFocusPainted(false);
        btnNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhanVien.setMargin(new java.awt.Insets(5, 14, 5, 14));
        btnNhanVien.setOpaque(false);
        btnNhanVien.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(btnNhanVien);
        btnNhanVien.setBounds(780, 70, 190, 110);

        btnHoaDon.setBackground(new java.awt.Color(123, 224, 219));
        btnHoaDon.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnHoaDon.setForeground(new java.awt.Color(0, 102, 0));
        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/basket-icon.png"))); // NOI18N
        btnHoaDon.setText("Bán hàng");
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseExited(evt);
            }
        });
        btnHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoaDonActionPerformed(evt);
            }
        });
        jPanel1.add(btnHoaDon);
        btnHoaDon.setBounds(50, 250, 190, 110);

        btnThongke.setBackground(new java.awt.Color(123, 224, 219));
        btnThongke.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnThongke.setForeground(new java.awt.Color(0, 102, 0));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/thongke-icon.png"))); // NOI18N
        btnThongke.setText("Thống kê - Báo cáo");
        btnThongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThongke.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnThongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongkeMouseExited(evt);
            }
        });
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongke);
        btnThongke.setBounds(540, 70, 190, 110);

        btnLogOut.setBackground(new java.awt.Color(123, 224, 219));
        btnLogOut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(204, 0, 0));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/logout-icon.png"))); // NOI18N
        btnLogOut.setText("Đăng xuất");
        btnLogOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogOut.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLogOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogOutMouseExited(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogOut);
        btnLogOut.setBounds(540, 250, 190, 110);

        btnChangePass.setBackground(new java.awt.Color(123, 224, 219));
        btnChangePass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(0, 102, 0));
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/change-pass.png"))); // NOI18N
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChangePass.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnChangePass.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePassMouseExited(evt);
            }
        });
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePass);
        btnChangePass.setBounds(290, 250, 190, 110);

        btnExit.setBackground(new java.awt.Color(123, 224, 219));
        btnExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/exit-icon.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(780, 250, 190, 110);

        jLabel3.setBackground(new java.awt.Color(0, 153, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QLNS/images/nenaaa.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1020, 435);

        panel3.setBackground(new java.awt.Color(0, 161, 12));

        txtRun.setBackground(new java.awt.Color(1, 169, 7));
        txtRun.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        txtRun.setForeground(new java.awt.Color(255, 255, 255));
        txtRun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtRun.setText("Cửa hàng Nông sản sạch - 30, Trường Chinh, Tp Huế, điện thoại: 0398218484, email: nongsansach@gmail.com");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRun, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtRun, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        try {
            new NhanVienJFrame().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnNongSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNongSanActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            new NongSanJFrame().setVisible(true);
        } catch (SQLException ex) {
            ex.printStackTrace();
        } catch (IOException ex) {
            ex.printStackTrace();

        }
        this.dispose();
    }//GEN-LAST:event_btnNongSanActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn đăng xuất!",
                "Đăng xuất", JOptionPane.YES_NO_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new LoginForm().setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachHangActionPerformed
        try {
            // TODO add your handling code here:
            new KhachHangJFrame().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnKhachHangActionPerformed

    private void btnHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoaDonActionPerformed
        try {
            // TODO add your handling code here:
            new HoaDonJFrame().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnHoaDonActionPerformed

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        // TODO add your handling code here:
        btnNhanVien.setBackground(new Color(235, 212, 23));
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        // TODO add your handling code here:
        btnNhanVien.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnNongSanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNongSanMouseEntered
        // TODO add your handling code here:
        btnNongSan.setBackground(new Color(235, 212, 23));
    }//GEN-LAST:event_btnNongSanMouseEntered

    private void btnNongSanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNongSanMouseExited
        // TODO add your handling code here:
        btnNongSan.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnNongSanMouseExited

    private void btnKhachHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseEntered
        // TODO add your handling code here:
        btnKhachHang.setBackground(new Color(235, 212, 23));
    }//GEN-LAST:event_btnKhachHangMouseEntered

    private void btnKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseExited
        // TODO add your handling code here:
        btnKhachHang.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnKhachHangMouseExited

    private void btnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseEntered
        // TODO add your handling code here:
        btnThongke.setBackground(new Color(235, 212, 23));
    }//GEN-LAST:event_btnThongkeMouseEntered

    private void btnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseExited
        // TODO add your handling code here:
        btnThongke.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnThongkeMouseExited

    private void btnHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseEntered
        // TODO add your handling code here:
        btnHoaDon.setBackground(new Color(235, 212, 23));

    }//GEN-LAST:event_btnHoaDonMouseEntered

    private void btnHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseExited
        // TODO add your handling code here:
        btnHoaDon.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnHoaDonMouseExited

    private void btnLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseEntered
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(235, 212, 23));
    }//GEN-LAST:event_btnLogOutMouseEntered

    private void btnLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseExited
        // TODO add your handling code here:
        btnLogOut.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnLogOutMouseExited

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        try {
            new ThongKeJFrame().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void btnChangePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassMouseEntered
        // TODO add your handling code here:
        btnChangePass.setBackground(new Color(235, 212, 23));

    }//GEN-LAST:event_btnChangePassMouseEntered

    private void btnChangePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassMouseExited
        // TODO add your handling code here:
        btnChangePass.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnChangePassMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(new Color(235, 212, 23));
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn thoát",
                "Thông báo", JOptionPane.OK_CANCEL_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
        } else
            btnChangePass.setBackground(new Color(123,224,219));
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:

        new ChangePassFrame().setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnChangePassActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNongSan;
    private javax.swing.JButton btnThongke;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblClock;
    private javax.swing.JPanel panel3;
    private javax.swing.JLabel txtRun;
    // End of variables declaration//GEN-END:variables

}
